name: Top GitHub Users
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Active Users
    runs-on: ubuntu-latest  # UPDATED
    steps:
      - uses: actions/checkout@v4  # UPDATED
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CUSTOM_TOKEN }}
      - uses: actions/setup-node@v4  # UPDATED
        with:
          node-version: 20  # UPDATED
      - uses: gayanvoice/top-github-users-action@master
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
